### ISSUE TITLE
Server Error 500 when trying to modify a extension

### ISSUE THREAD

**Issue by Apehaenger** [djangopbx/djangopbx#13]
Tried going on in using DjangoPBX, but got stopped early ;-)

When trying to modify an extension, I do get "Server Error 500" with the following traceback:
```
ERROR Internal Server Error: /admin/accounts/extension/41eb87c4-8862-4a26-8a46-6d24934aa76e/change/
Traceback (most recent call last):
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1944, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/django-pbx/pbx/accounts/admin.py", line 295, in save_model
    efsf.es_disconnect()
  File "/home/django-pbx/pbx/accounts/extensionfunctions.py", line 75, in es_disconnect
    self.es.disconnect()
    ^^^^^^^
AttributeError: 'ExtFeatureSyncFunctions' object has no attribute 'es'
```

Looks like the failure is somewhere here: [https://github.com/djangopbx/djangopbx/blob/199af36e532b37c16f481e4e42b3bc43d73bda29/accounts/extensionfunctions.py#L46 between ](https://github.com/djangopbx/djangopbx/blob/199af36e532b37c16f481e4e42b3bc43d73bda29/accounts/extensionfunctions.py#L46-L51)
(early constructor exit before es class var got created)

I do have a lot of ideas how to fix/work around, but guess all are bad :-/
Might take a look please?

**Comment by AdrianFretwell** [comment]
Hi Apehaenger,
You are exactly right.  - And, thank you for your help.
To save CPU with not needed initialisation, init exits early if it determines that Feature-Sync is not possible.

I have added an "es_connected" flag that member functions can test and return if False.
Looks OK testing here, let me know how you get on.
I will always welcome your ideas for fix/work around, there is often more than one way of doing something.
Kind regards,
Adrian.

**Comment by Apehaenger** [comment]
Quite cool, thx! It's working now!

BTW: What's the preferred way for live developing?
You know?!:
When I'm via VSCODE remotely connected to the machine running DjangoPBX. After Django code change I manually need to do an `uwsgi --reload /var/run/uwsgi/app/djangopbx/pid`? Or is there some more comfortable way?

**Comment by AdrianFretwell** [comment]
I always run the Django development server, with DEBUG = True in settings.py
https://docs.djangoproject.com/en/5.0/intro/tutorial01/

I ssh into my development server two times (once from each screen) then in one I run:
python3 manage.py runserver 0:8080
and in the other screen I do the editing.

This gives me a live screen where I can see both syntax checking and web requests, and also any output from temporary print() statements that I sometimes use to check the value of a variable.

I hope that helps.

**Comment by Apehaenger** [comment]
Quite thanks for the info. Will try that next time ;-)
